export default {
  "banheiros|Jogo de toalhas": 300,
  "banheiros|Kit de cerâmica": 180,
  "banheiros|Tapetes para banheiro": 200,
  "banheiros|Toalheiro térmico": 700,
  "cozinha|Air fryer": 450,
  "cozinha|Aparelho de jantar": 500,
  "cozinha|Assadeiras": 250,
  "cozinha|Cafeteira": 450,
  "cozinha|Coifa": 1200,
  "cozinha|Conjunto de bowls": 200,
  "cozinha|Cooktop + forno elétrico": 2400,
  "cozinha|Faqueiro": 400,
  "cozinha|Frigideiras": 300,
  "cozinha|Geladeira": 3000,
  "cozinha|Jogo de café": 250,
  "cozinha|Jogo de panelas": 800,
  "cozinha|Jogo de talheres": 300,
  "cozinha|Liquidificador": 300,
  "cozinha|Micro-ondas": 700,
  "cozinha|Mixer": 250,
  "cozinha|Panela de pressão": 250,
  "cozinha|Potes herméticos": 250,
  "experiencias|Alimentação durante a viagem": 800,
  "experiencias|Cota livre para a lua de mel": 300,
  "experiencias|Cota livre para uma experiência": 300,
  "experiencias|Cota para a lua de mel": 150,
  "experiencias|Cota para uma experiência": 150,
  "experiencias|Deslocamentos": 500,
  "experiencias|Hospedagem": 2000,
  "experiencias|Passagens aéreas": 2000,
  "experiencias|Passeio especial": 600,
  "experiencias|Passeio ou experiência": 700,
  "experiencias|Passeios durante a lua de mel": 800,
  "lavanderia|Aspirador de pó": 700,
  "lavanderia|Ferro de passar roupa": 250,
  "lavanderia|Lava e seca": 3000,
  "lavanderia|Varal ou organizador": 200,
  "quarto|Ar-condicionado": 2500,
  "quarto|Colchas": 500,
  "quarto|Edredom": 450,
  "quarto|Jogo de lençol": 350,
  "sala|Almofadas": 250,
  "sala|Cadeiras de jantar": 1500,
  "sala|Caixa de som": 800,
  "sala|Jogo americano": 200,
  "sala|Manta de sofá": 250,
  "sala|Mesa de jantar": 2000,
  "sala|Sofá": 3000,
  "sala|Tapete para sala": 1000,
  "sala|Televisão": 2000,
  "sala|Toalha de mesa": 250,
  "sala|Vasos decorativos": 300
};
